spring:
  application:
    name: spring-data
  datasource:
    url: jdbc:postgresql://localhost:5432/rtracee?useSSL=false
    username: rtracee
    password: school21
    driver-class-name: org.postgresql.Driver
